import 'package:fairteams/model.dart';

Map<String, Group> loadSampleGroups() {
  Group group = Group(name: 'Tuesday Football', sport: 'football', skillNames: [
    'Defence',
    'Mistakes',
    'Fitness',
    'Savvy',
    'Goals'
  ], players: [
    Player(name: 'Alan', skills: {
      'Defence': 9.0,
      'Mistakes': 9.0,
      'Fitness': 6.0,
      'Savvy': 6.0,
      'Goals': 4.0,
    }),
    Player(name: 'Andi', skills: {
      'Defence': 6.0,
      'Mistakes': 8.0,
      'Fitness': 4.0,
      'Savvy': 7.0,
      'Goals': 6.0,
    }),
    Player(name: 'Chris', skills: {
      'Defence': 6.0,
      'Mistakes': 8.0,
      'Fitness': 7.0,
      'Savvy': 7.0,
      'Goals': 6.0,
    }),
    Player(name: 'Craig', skills: {
      'Defence': 7.0,
      'Mistakes': 7.0,
      'Fitness': 5.0,
      'Savvy': 7.0,
      'Goals': 7.0,
    }),
    Player(name: 'Dil', skills: {
      'Defence': 3.0,
      'Mistakes': 3.0,
      'Fitness': 3.0,
      'Savvy': 2.0,
      'Goals': 3.0,
    }),
    Player(name: 'Dougal', skills: {
      'Defence': 5.0,
      'Mistakes': 8.0,
      'Fitness': 9.0,
      'Savvy': 5.0,
      'Goals': 6.0,
    }),
    Player(name: 'Eugene', skills: {
      'Defence': 4.0,
      'Mistakes': 5.0,
      'Fitness': 6.0,
      'Savvy': 8.0,
      'Goals': 9.0,
    }),
    Player(name: 'Evan', skills: {
      'Defence': 7.0,
      'Mistakes': 7.0,
      'Fitness': 5.0,
      'Savvy': 10.0,
      'Goals': 8.0,
    }),
    Player(name: 'Greig', skills: {
      'Defence': 9.0,
      'Mistakes': 9.0,
      'Fitness': 8.0,
      'Savvy': 6.0,
      'Goals': 6.0,
    }),
    Player(name: 'John-Luke', skills: {
      'Defence': 7.0,
      'Mistakes': 7.0,
      'Fitness': 6.0,
      'Savvy': 5.0,
      'Goals': 5.0,
    }),
    Player(name: 'Joe', skills: {
      'Defence': 9.0,
      'Mistakes': 7.0,
      'Fitness': 8.0,
      'Savvy': 5.0,
      'Goals': 4.0,
    }),
    Player(name: 'Josh', skills: {
      'Defence': 6.0,
      'Mistakes': 6.0,
      'Fitness': 3.0,
      'Savvy': 7.0,
      'Goals': 4.0,
    }),
    Player(name: 'Mark', skills: {
      'Defence': 3.0,
      'Mistakes': 7.0,
      'Fitness': 5.0,
      'Savvy': 8.0,
      'Goals': 7.0,
    }),
    Player(name: 'Peter', skills: {
      'Defence': 4.0,
      'Mistakes': 8.0,
      'Fitness': 8.0,
      'Savvy': 7.0,
      'Goals': 6.0,
    }),
    Player(name: 'Robin', skills: {
      'Defence': 6.0,
      'Mistakes': 8.0,
      'Fitness': 6.0,
      'Savvy': 7.0,
      'Goals': 6.0,
    }),
    Player(name: 'Spybey', skills: {
      'Defence': 7.0,
      'Mistakes': 8.0,
      'Fitness': 7.0,
      'Savvy': 6.0,
      'Goals': 4.0,
    }),
    Player(name: 'Stefan', skills: {
      'Defence': 3.0,
      'Mistakes': 3.0,
      'Fitness': 5.0,
      'Savvy': 3.0,
      'Goals': 3.0,
    }),
    Player(name: 'Steve', skills: {
      'Defence': 8.0,
      'Mistakes': 9.0,
      'Fitness': 8.0,
      'Savvy': 10.0,
      'Goals': 10.0,
    }),
    Player(name: 'Tim', skills: {
      'Defence': 7.0,
      'Mistakes': 8.0,
      'Fitness': 9.0,
      'Savvy': 10.0,
      'Goals': 10.0,
    }),
    Player(name: 'Tom', skills: {
      'Defence': 8.0,
      'Mistakes': 6.0,
      'Fitness': 9.0,
      'Savvy': 6.0,
      'Goals': 5.0,
    }),
  ]);
  return {group.id: group};
}
